spring.application.name=ComicHub

spring.datasource.url=jdbc:mysql://comic-hub-lp2.mysql.database.azure.com:3306/comichub_bd?sslMode=REQUIRED&serverTimezone=UTC
spring.datasource.username=comicHubMysql
spring.datasource.password=(0mi(HUPM!$Q/

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect